use condition to look into err2.txt

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -100,9 +100,9 @@ jobs:
         id: getoutput
         run: |
           echo "::set-output name=contents::$(cat err2.txt)"
-          echo ${{ steps.getoutput.outputs.contents }}
       - name: Check if all tests passed
-#        if: ${{ contains(steps.getoutput.outputs.contents, 'FAILED (failures=' ) }}
         run: |
-          echo "${{ steps.getoutput.outputs.contents }}"
-          exit 1
+          if grep -q "FAILED (failures=" err2.txt; then
+            echo "There are tests failed."
+            exit 1
+          fi
