test if py3 will fail

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,10 +50,11 @@ jobs:
         id: getoutput
         run: echo "::set-output name=contents::$(cat err.txt)"
       - name: Check if all tests passed
-        if: contains( steps.getoutput.outputs.contents , 'FAILED (failures=' )
         run: |
-          echo "${{ steps.getoutput.outputs.contents }}"
-          exit 1
+          if grep -q "FAILED (failures=" err2.txt; then
+            echo "There are tests failed."
+            exit 1
+          fi
   codecov-python-27:
     runs-on: ubuntu-latest
     container:
