revert unit test to be good

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -119,10 +119,15 @@ jobs:
           fail_ci_if_error: true
       - name: Read test output
         id: getoutput
-        run: echo "::set-output name=contents::$(cat err2.txt)"
-      - name: Check if all tests passed
-        if: contains( steps.getoutput.outputs.contents, 'FAILED (failures=' )
-        shell: cmd
         run: |
-          echo "${{ steps.getoutput.outputs.contents }}"
-          exit 1
+          echo "CONTENTS=$(cat err2.txt)" > $GITHUB_ENV
+      - name: Check if all tests passed
+        shell: bash
+        run: |
+          CONTENTS=$(cat err2.txt)
+          echo "Contents: $CONTENTS"
+          if echo "$CONTENTS" | grep -q 'FAILED (failures='; then
+            echo "There are failed tests"
+            echo "$CONTENTS"
+            exit 1
+          fi
