use bash shell instead of cmd

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,15 +49,15 @@ jobs:
       - name: Read test output
         id: getoutput
         run: |
-          echo "contents=$(cat err.txt)" > output.txt
+          echo "CONTENTS=$(cat err.txt)" >> $GITHUB_ENV
       - name: Check if all tests passed
-        shell: cmd
+        shell: bash
         run: |
-          findstr /C:"FAILED (failures=" output.txt >nul
-          if errorlevel 1 (
-            type output.txt
-            exit /b 1
-          )
+          if echo "$CONTENTS" | grep -q 'FAILED (failures='; then
+            echo "There are failed tests"
+            echo "$CONTENTS"
+            exit 1
+          fi
   codecov-python-27:
     runs-on: windows-latest
     needs: codecov-python-39
